node {
		stage('Checkout') 
		{
			checkout scm
    	}	
    
    	dir("spree_dev-main")
    	{
    		stage('Docker Build Publish') 
			{
				    docker.withRegistry('https://registry.hub.docker.com', 'pih-dockerhub-id') {

				        def customImage = docker.build("pihddev/fth-yeewu-spree-ruby-test:spree-version${env.BUILD_ID}")

				        /* Push the container to the custom Registry */
				        customImage.push()
				    }
    		}	
    	}

}