node {
    checkout scm

    docker.withRegistry('https://registry.hub.docker.com', 'pih-dockerhub-id') {

        def customImage = docker.build("fth-yeewu-spree-ruby-test/spree-image:${env.BUILD_ID}")

        /* Push the container to the custom Registry */
        customImage.push()
    }
}